name: C++ CI - macOS

on:
  push:
    branches:
      - main
      - feature/github_actions

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Debug - Start
        run: echo "Starting the job"

      - name: Install dependencies on macOS
        run: |
          brew update
          brew install boost cmake open-mpi

      - name: Debug - Post install
        run: echo "Dependencies installed"

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        run: |
          cd build
          cmake .. -DPATCH_VERSION=${{ github.run_number }}
          
      - name: Build the project
        run: |
          cd build
          cmake --build .

      - name: Run tests
        run: |
          cd build
          cmake --build . --target test

      - name: Create package for macOS
        run: |
          cd build
          cmake --build . --target package

      # Проверка существования пакета для macOS 
      - name: Check if macOS package exists 
        run: | 
          if [ -f "./IFilterProject-0.1.0-Darwin.dmg" ]; then 
            echo "macOS package exists." 
          else 
            echo "macOS package does not exist." 
            exit 1 
          fi 

      # Создание Release для macOS 
      - name: Create Release for macOS 
        id: create_release_macos 
        uses: actions/create-release@v1 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
           tag_name: "release-macos-${{ github.run_number }}" 
           release_name: "Release macOS ${{ github.run_number }}" 
           draft: false 
           prerelease: false 

      # Загрузка артефактов для macOS 
      - name: Upload Release Asset (macOS) 
        uses: actions/upload-release-asset@v1 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          upload_url: ${{ steps.create_release_macos.outputs.upload_url }} 
          asset_path: ./build/IFilterProject-0.1.0-Darwin.dmg  
          asset_name: IFilterProject-0.1.0-Darwin.dmg  
          asset_content_type: application/x-apple-diskimage 

      - name: Debug - End  
        run: echo "Ending the job"
