name: C++ CI

on:
  push:
    branches:
      - main
      - feature/github_actions

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  # Добавляем macOS в матрицу
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60  # Увеличьте время выполнения, если это необходимо

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Debug - Start
        run: echo "Starting the job"

      - name: Install dependencies on Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libboost-all-dev \
            cmake \
            openmpi-bin \
            libopenmpi-dev

      - name: Install dependencies on macOS
        if: ${{ runner.os == 'macOS' }}
        run: |
          brew update
          brew install boost cmake open-mpi

      # Отладка перед сборкой
      - name: Debug - Post install
        run: echo "Dependencies installed"

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        run: |
          cd build
          cmake .. -DPATCH_VERSION=${{ github.run_number }}
          
      - name: Build the project
        run: |
          cd build
          cmake --build .

      - name: Run tests
        run: |
          cd build
          cmake --build . --target test

      - name: Create package
        run: |
          cd build
          cmake --build . --target package

      # Отладка перед проверкой существования пакета для Linux
      - name: Debug - List contents of build directory after package creation (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: ls -l ./build

      # Проверка существования пакета для Linux
      - name: Check if Linux package exists
        if: ${{ runner.os == 'Linux' }}
        run: |
          if [ -f "./build/IFilterProject-0.1.0-Linux.sh" ]; then  # Убедитесь, что имя файла правильное
            echo "Linux package exists."
          else
            echo "Linux package does not exist."
            exit 1
          fi

      # Проверка существования пакета для macOS
      - name: Check if macOS package exists
        if: ${{ runner.os == 'macOS' }}
        run: |
          if [ -f "./build/IFilterProject-0.1.0-Darwin.dmg" ]; then  # Убедитесь, что имя файла правильное для macOS
            echo "macOS package exists."
          else
            echo "macOS package does not exist."
            exit 1
          fi

      # Создание релиза для Linux
      - name: Create Release for Linux
        if: ${{ runner.os == 'Linux' }}
        id: create_release_linux
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "release-linux-${{ github.run_number }}"
          release_name: "Release Linux ${{ github.run_number }}"
          draft: false
          prerelease: false

      # Загрузка артефактов для Linux
      - name: Upload Release Asset (Linux)
        if: ${{ runner.os == 'Linux' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_linux.outputs.upload_url }}
          asset_path: ./build/IFilterProject-0.1.0-Linux.sh  # Убедитесь, что путь правильный для созданного пакета 
          asset_name: IFilterProject-0.1.0-Linux.sh 
          asset_content_type: application/x-sh

      # Создание релиза для macOS
      - name: Create Release for macOS
        if: ${{ runner.os == 'macOS' }}
        id: create_release_macos
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "release-macos-${{ github.run_number }}"
          release_name: "Release macOS ${{ github.run_number }}"
          draft: false
          prerelease: false

      # Загрузка артефактов для macOS
      - name: Upload Release Asset (macOS)
        if: ${{ runner.os == 'macOS' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_macos.outputs.upload_url }}
          asset_path: ./build/IFilterProject-0.1.0-Darwin.dmg  # Убедитесь, что путь правильный для созданного пакета 
          asset_name: IFilterProject-0.1.0-Darwin.dmg 
          asset_content_type: application/x-apple-diskimage 

      - name: Debug - End
        run: echo "Ending the job"
      
      - name: Debug - List all files in build directory at the end of the job
        run: |
          echo "Current directory:"
          pwd
          echo "List of files in build directory:"
          ls -la ./build
